service: fastapi-lambda-app
projectDir: ./

package:
  individually: true

provider:
  name: aws
  runtime: python3.9
  region: us-east-1
  stage: ${opt:stage, "dev"}

plugins:
  - serverless-python-requirements

layers:
  myprojWithDependencies:
    package:
      artifact: dist/myproj-lambda-layer.zip
    description: The myproj package and its dependencies
    compatibleRuntimes:
      - python3.9


functions:
  app:
    package:
      include:
        - "./api/main.py"
    module: api
    handler: main.handler
    environment:
      STAGE: ${self:provider.stage}
    layers:
      - { Ref: MyprojWithDependenciesLambdaLayer }
    events:
      - http:
          method: any
          path: /{proxy+}
